name: hashit
version: 3.1.3
summary: hashit
icon: icon.png
description: |
  Hashit is an hashing program which can be uses to hash and verify muliple files on a system.
  I got the idea from an ubuntu iso image which have this hash table, so i got the idea to make
  such a program using python.

grade: stable
confinement: classic

apps:
  hashit:
    command: bin/hashit

parts:
  hashit:
    plugin: python
    python-version: python3
    python-packages: ["argc"]
    source: .
