theme: jekyll-theme-midnight
description: Hashit an hashing application
show_downloads: True

github:
  owner_url: https://github.com/JavadSM/hashit/
  tar_url: https://github.com/JavadSM/hashit/raw/master/release/hashit.tar
  zip_url: https://github.com/JavadSM/hashit/raw/master/release/hashit.zip

author:
  name: Javad Shafique
  url: javadsm.wordpress.com

layout: default
markdown: kramdown
extra: "Hosted with love on github"

plugins:
  - jekyll-relative-links